name: 'CI-main'

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '1'
        ref: 'main'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Verify build dependencies
      run: |
        python --version
        pip --version
        make --version
        docker --version
    - name: Install app dependencies
      run: |
        make -l init_ci
    - name: Run all
      run: |
        make -l run_all
    - name: Archive unit test report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: tests_integration_report
        path: tests_integration_report.html
    - name: Archive integration test report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: tests_integration_report
        path: tests_integration_report.html
    - name: Build docker image
      run: |
        make docker